# only gitlab section is mandatory
[gitlab]
url = "https://gitlab.com"
token = "your-token-here"

# optional
[server]
ip = "0.0.0.0"
port = 8080
workers = 4

# optional
[cache]
ttl_group_seconds = 300
ttl_project_seconds = 300
ttl_branch_seconds = 60
ttl_job_seconds = 5
ttl_pipeline_seconds = 5
ttl_schedule_seconds = 300
ttl_artifact_seconds = 1800

# optional
[pipeline]
history_days = 5

# optional
[project]
skip_ids = []

# optional
[group]
only_ids = []
skip_ids = []
only_top_level = true
include_subgroups = true

# optional
[ui]
read_only = true
hide_write_actions = false
page_size_options = [10, 20, 30, 40, 50]
default_page_size = 10
